baseURL = "https://angaza-elimu.github.io"
languageCode = "en-us"
title = "React-Offline-Sync"
theme = "color-your-world"

[menu]
    [[menu.main]]
        identifier = "install"
        name = "Installation"
        url  = "/"
        weight = 1
        


    